### ISSUE TITLE
Google maps is very comprehensive and comes at a cost

### ISSUE THREAD

**Issue by tapjay** [Covid-Mutual-Aid/search-by-postcode#11]
Explore switching to mapbox or open street maps?

**Comment by conatus** [comment]
@janbaykara has some experience with Mapbox.

**Comment by matthewk** [comment]
I have asked Google for a free license for the google maps API

**Comment by ColmMassey** [comment]
@tapjay, would you be interested in using our software as an alternative to displaying the mutual aid data in a directory/map in Google? We could publish the data as a 'Linked Data', and view it with our map/directory front end. See https://oxford.solidarityeconomy.coop/ for example. 
We can handle larger data sets too. We are about the publish this one 
https://dotcoop.solidarityeconomy.coop/?showDatasetsPanel=false&htmlTitle=.coop

**Comment by tapjay** [comment]
@ColmMassey Thanks for your offer! However because we are allowing people to submit groups and are manually editing group details, we need to be able to ensure the content is up to date, also because others are using this as a primary data source. What you have linked me looks great though :-)

**Comment by robmorrissey** [comment]
Would it be a good opportunity to collaborating on implementing the maps in leaflet maybe? Julian has mentioned moving to Leaflet, and if Colm could contribute a pull request to the app with something starting that off it might be really cool?

**Comment by ColmMassey** [comment]
You wouldn't need to change anything you are currently doing at the moment. Our scripts would automatically take your data sheet and republish it as linked data (https://en.wikipedia.org/wiki/Linked_data) as frequently as required. It would simply augment the accessibility of the lists you are building. You could embed this map in your website as well as the Google one. 
It would automatically provide multiple apis to the data. We are also working with others to publish other data sets in this way so that it will be trivial to overlay mutual aid groups with co-operatives, for example. It will be possible to write database queries spanning both data sets. 
We were going to build a test map anyway for you to take a look at. Would make it easier to discuss the possibilities.

**Comment by robmorrissey** [comment]
Would you be keen on contributing your knowledge to the codebase? I think
the goal is to keep it open and allow other groups to fork simply through
github.

**Comment by ColmMassey** [comment]
All our code is on Github already. https://github.com/solidarityeconomyassociation.

**Comment by robmorrissey** [comment]
So you’d be up for submitting a pull request? Would be great to have your
input. There’s a Slack where we coordinate:
https://join.slack.com/t/code4covid/shared_invite/zt-cms2o7rm-FtmF~455wnm6ce108Gqggg

**Comment by tapjay** [comment]
I'll close this issue for now as my reason for opening this issue has since been resolved.
